version: '3.1'

services:

  mariadb_db:
    image: mariadb
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    volumes:
     - "${PWD}/data:/var/lib/mysql"
    ports:
      - 3306:3306
