version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
     # POSTGRES_USER: root
      POSTGRES_DB: test
    volumes:
        - "${PWD}/data:/var/lib/postgresql/data"
    ports:
        - 5432:5432

